### ISSUE TITLE
Update arxiv papers

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#3]
Scrape 552 new papers without content. Review list recently published papers and trace citations.

**Comment by jknowak** [comment]
Do you mean "scrape **has** 552 new papers without content"? I think the reason is, that for the ArXiv papers the code relies on Arxiv Vanity to parse papers and those that are not on the ArXiv Vanity are saved as "n/a" entries. I can see what can be those with it, just want to make sure that your wording is dealing with those papers and not finding new ones (although this could be split into a new issue) because from what I see the papers are scraped based on the manually updated CSV list.

**Comment by ccstan99** [comment]
Yes, the Nov 2022 scrape has 1446 entries of which 522 have no title or content. See the bottom of [arxiv_papers.jsonl](https://docs.google.com/spreadsheets/d/1yb5nLp5s9hPBFNVw2SGTRwHWNz2PjrsVYwL1JdiW06Y/edit#gid=1327583142). My guess is they were manually added to the CSV list but don't have associated content, maybe something related to arxiv vanity you mentioned. The June 2022 scrape didn't have this issue.

We're not dealing with completely new ones yet, which has a generic placeholder issue https://github.com/StampyAI/alignment-research-dataset/issues/6

**Comment by ccstan99** [comment]
Not sure if this'll help you for langchain has some document loaders for processing arxiv files:
https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/arxiv.html
