### ISSUE TITLE
ID's based on url

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#41]
Currently, IDs are hashed based on the text content. For some sources like stampy and blogs, the content may change but we'd like the hash to remain the same. So, let's hash it by url and possibly title also if we don't have a good/unique url. For stampy, don't use the title since that can change.

**Comment by mruwnik** [comment]
urls should be unique, if available. Should this apply to everything that has a unique url (i.e. just not ebooks for now)?

**Comment by ccstan99** [comment]
The suggestion (by chatgpt hallucinations) was to use a Goodreads link, i.e. https://www.goodreads.com/book/show/50485582-the-precipice

**Comment by Thomas-Lemoine** [comment]
My brother and I talked about it and a possibility is to change it so the id is based on the title + url, instead of making it custom-based on the source, but defaulting to just the text. Is there an advantage to using the text key? Can you think of any different entries that would have the same title and url? @mruwnik @ccstan99

**Comment by ccstan99** [comment]
Alignment newsletters and a few other newsletters (https://importai.substack.com, https://newsletter.mlsafety.org/) that summarize papers or blogs might have the same url as the original document they're summarizing. We can discuss whether that's what we really want though.

As mentioned in the original issue description, Stampy questions and possibly some blog posts could change their title while keeping the same url. So IDs that use urls + title might not catch the change and end up with duplicates in our db.

**Comment by Thomas-Lemoine** [comment]
Hmm I see, good point. I guess we might not even want there to be a newsletter entry AND a non-newsletter entry for the same title+url, since that would mean the text is duplicated so found twice using semantic search (the semantic search would yield the same embedding vectors for both entries). 

It's kind of tricky to avoid this. Seems like we'd need to do something like create the .jsonl datasets for the newsletter sources first, and then for each arxiv paper, or whatever else, that we add, we'd need to first verify that they aren't already in a newsletter. Or something. For this current issue I could create the id based on source + title + url, to remove duplicates between newsletter entries and non-newsletter entries. Does that work?

**Comment by Thomas-Lemoine** [comment]
That doesn't work for different chapters of a book being different entries: same title, url and source

**Comment by Thomas-Lemoine** [comment]
but then if we're using title + url + source + text, any of it can change. So it seems like that means we need to change the add_id and verify_id methods for entries whose text can change. default can be source+text, since within a source the text is (afaik) never gonna repeat; and then, for texts that can change overtime, we add the add_id and verify_id methods and make them be based on different keys that will not change

**Comment by Thomas-Lemoine** [comment]
a possibly simpler option is to have each dataset have a list of fields that we ensure will stay constant. So in the __init__ for arbital, 
we have 
```
ARBITAL_REGISTRY = [Arbital(name='arbital', const_fields = ['text'])]
```
and so on for different sources, some would have ['source', 'url'] for example. Then, we use these values to create the id so that the add_id and verify_id methods don't have to be modified based on the specific source.

**Comment by Thomas-Lemoine** [comment]
Oh actually since add_id and validate_id are in the DataEntry class, it would be like: 
```
def process_entry(self, alias):
        try:
            page = self.get_page(alias)
            summary, text = extract_text(page['text'])

            return DataEntry({
                'title': page['title'] if 'title' in page else 'n/a',
                'text': text,
                'date_published': self._get_published_date(page),
                'url': f'https://arbital.com/p/{page.get("alias") or alias}',
                'source': self.name,
                'source_type': 'text',
                'authors': self.extract_authors(page),
                'alias': alias,
                'tags': list(filter(None, map(self.get_title, page['tagIds']))),
                'summary': [summary] if summary else [],
            }, const_fields = ['text'])
        except Exception as e:
            logger.error(f"Error getting page {alias}: {e}")
        return None
```
